node {
    def IMAGE_NAME = "react-app"
    def CONTAINER_NAME ="vigilant_ishizaka"

    stage('Clone Code') {
        git branch: 'main',
            url: 'https://github.com/Hawk1509/NSDC.git'
    }

    stage('Build Docker Image') {
        sh "docker build -t ${IMAGE_NAME} ."
    }

    stage('Stop Old Container') {
        sh """
        docker stop ${CONTAINER_NAME} || true
        docker rm ${CONTAINER_NAME} || true
        """
    }

    stage('Run Docker Container') {
        sh """
        docker run -d \
          -p 5173:5173 \
          --name ${CONTAINER_NAME} \
          ${IMAGE_NAME}
        """
    }

    echo "React app deployed using Docker successfully 🎉"
}
